spring:
  application:
    name: pw-parking-permit
#----------------------------------------
# Open API
#----------------------------------------
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'

#----------------------------------------
# Camunda
#----------------------------------------
camunda:
  bpm:
    client:
      base-url: ${config.camunda.base-url}
    deployment:
      processes:
        - name: Parking permit process
          tenant: PARKING_PERMIT
          bpmnResourcePattern: classpath*:processmodels/*.bpmn
          dmnResourcePattern: classpath*:processmodels/*.dmn
          formResourcePattern: classpath*:processmodels/*.form
  worker:
    max:
      retries: 3
    retry:
      timeout: 10

#----------------------------------------
# Camunda integration settings
#----------------------------------------
# Rest client
integration:
  camunda:
    connectTimeout: 5
    readTimeout: 20
    url: ${config.camunda.base-url}