spring:
  application:
    name: pw-parking-permit-it
#----------------------------------------
# Open API
#----------------------------------------
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'

#----------------------------------------
# Camunda
#----------------------------------------

camunda:
  bpm:
    client:
      base-url: http://replaced_by_test:8080
  
#----------------------------------------
# Camunda integration settings
#----------------------------------------
# Rest client
integration:
  camunda:
    connectTimeout: 5
    readTimeout: 20
    url: http://replaced_by_test:8080
